name: pyart-docs
channels:
  - conda-forge
dependencies:
  - gdal
  - numpy
  - scipy
  - matplotlib
  - pandas
  - netcdf4
  - pytest
  - wradlib
  - metpy
  - cartopy
  - cvxopt
  - xarray
  - sphinx
  - ipython
  - pandoc
  - pkg-config
  - Cython
  - fsspec
  - s3fs
  - gcsfs>=2025.3.2
  - glpk
  - cftime
  - shapely
  - open-radar-data
  - myst-nb
  - pydata-sphinx-theme
  - sphinx-gallery
  - sphinx-design
  - sphinx-copybutton
  - nbsphinx
  - pre_commit
  - cmweather
  - mda-xdrlib
  - xradar
  - dask
  - ablog
  - pip
  - pip:
      - pooch
      - versioneer
